config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :telegram
  resources :orders

  namespace :api do
    resources :stages
    resources :partners
    resources :order_objects do
      collection do
        post :selector
        post :object_container
      end
    end
    resources :characters do
      collection do
        post :available
        post :partner_container
      end
    end
    resources :contacts do
      collection do
        get :check
      end
    end
    resources :actors do
      collection do
        post :time_table
        post :occupation_time
      end
    end
    resources :price_positions
    resources :costume_price_positions
    resources :orders do
      collection do
        post :validate
      end
    end
    resources :characters_groups
    resources :performances
    resources :order_sources
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  attr_accessor :is_new_order, :is_new_stage

  belongs_to :customer
  belongs_to :performance
  belongs_to :stage
  belongs_to :order_source

  has_many :orders_characters
  accepts_nested_attributes_for :orders_characters, allow_destroy: true

  has_many :characters, through: :orders_characters

  has_many :positions, dependent: :destroy

  enum source: [:partner, :site, :commercial]

  validates :child_name, :child_birthday, :performance_date, :performance_time,
            :guests_age_from, :guests_age_to, :additional_expense, presence: true

  belongs_to :contact

  enum status: [:fresh, :assigned, :prepared, :done, :canceled_by_customer, :canceled_by_owner, :failed, :approved]

  scope :no_actor, ->{
    order_ids = Position.all.group_by{|p| p.order_id}.select do |_order_id, positions|
      positions.sum{|p| p.invitations.count}.zero?
    end.keys
    Order.where(id: order_ids)
  }

  scope :today, ->{ where(performance_date: [Date.today, Date.tomorrow]) }
  scope :seven_days, ->{ where(performance_date: (Date.today.ago(7.days)..Date.today)) }
  scope :two_weeks, ->{ where(performance_date: (Date.today.ago(14.days)..Date.today)) }

  def sent_invitations_to_all
    invitations = positions.map(&:invitations).flatten
    invitations.select do |i|
      if i.status == 'empty'
        i.fire_events!(:sent_invitation)
      elsif i.status == 'sent'
        i.fire_events!(:sent_again)
      end
    end
  end

end

app/controllers/api/orders_controller.rb
class Api::OrdersController < ApplicationController

  def validate
    errors = {order: {}}
    contact_validator = Validators::Contact.new(contact_params)
    contact_validator.validate
    errors[:order].merge!(contact_validator.errors)

    customer_validator = Validators::Customer.new(customer_params)
    customer_validator.validate
    errors[:order].merge!(customer_validator.errors)

    stage_validator = Validators::Stage.new(stage_params)
    stage_validator.validate
    errors[:order].merge!(stage_validator.errors)

    order = Order.new(order_params)
    order.valid?
    errors[:order].merge!(order.errors.to_h)

    if positions_params
      positions_validator = Validators::Positions.new(positions_params, order_params.include?('id'), nil)
      positions_validator.validate
      errors[:order].merge!(positions_validator.errors)
    else
      errors[:order][:positions] = 'Нужно выбрать персонажа или представление'
    end

    render json: { errors: ErrorsSerializer.new(errors).serialize }
  end

  def customer_params
    params.require(:order).permit(:is_new_order, :customer_id, customer: [:name, :customer_type])
  end

  def contact_params
    params.require(:order).permit(:is_new_order, :contact_id, contact: [:value, :notice])
  end

  def stage_params
    params.require(:order).permit(:is_new_stage, :stage_id,
                                  stage: [:district, :street, :house, :apartment, :description])
  end

  def order_params
    params.require(:order).permit(:id, :source, :child_name, :child_notice, :child_birthday,
                                  :guests_age_from, :guests_age_to, :performance_date,
                                  :performance_time, :performance_duration, :partner_money,
                                  :exclude_additional_expense, :exclude_additional_outcome, :partner_payed,
                                  :additional_expense, :order_calculations_notice)

  end

  def positions_params
    if params[:order].keys.include?('positions')
      params.require(:order).require(:positions).permit!
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include ParamsParsing

  def new
    @partner = Customer.where(customer_type: Customer.customer_types[:partner], partner_link: params[:partner_key]).first

    @objects = Performance.all.map{|p| [p.name, "performances_#{p.id}"]} +
      CharactersGroup.all.map{|cg| [cg.name, "characters_groups_#{cg.id}"]}
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    order = Order.new
    common_data = params[:order_info].first.last
    order.performance_date = common_data[:date]
    order.child_name = common_data[:childName]
    order.child_birthday = Date.today
    order.performance_time = DateTime.now
    order.guests_age_from = 20
    order.guests_age_to = 30
    order.additional_expense = 0
    # ??? to guests notice ?
    order.guests_notice = common_data[:orderNotice]
    order.child_notice = common_data[:childNotice]
    customer = Customer.find(params[:partner_id])
    order.customer_id = customer.id
    order.stage_id = customer.stages.first.id
    order.contact_id = customer.contacts.first.id
    order.performance_duration = common_data[:duration]
    # todo : change this
    order.order_source_id = OrderSource.find(2)
    params[:order_info].each do |_character_id, position_info|
      start = position_info[:maxTimeRange][:start].to_i
      stop = position_info[:maxTimeRange][:stop].to_i
      date = Date.parse(position_info[:date])
      character_id = position_info[:characterId]
      owner = extract_object_from_description(position_info[:ownerInfo])
      position_notice = "Продолжительность #{position_info[:duration]} минут"
      position_notice << $RS
      position_notice << "Желаемое время: #{position_info[:timeRanges].map{|index, range| "#{range[:start]}:00 - #{range[:stop]}:00" }.join(', ')}"
      order.positions << Position.new(
        start: create_date_time(date, start),
        stop: create_date_time(date, stop),
        character_id: character_id,
        order_notice: position_notice,
        owner_class: owner.class,
        fixed_start: true,
        fixed_stop: true,
        owner_id: owner.id
      )
    end
    if order.save
      render json: { status: 200 , order_id: order.id, valid: order.valid?, errors: order.errors.full_messages }
    else
      render json: { status: 422 }
    end
  end

  private

  # create DateTime from Date and Time with
  # correct Time Zone
  def create_date_time(d, hour)
    DateTime.new.in_time_zone(Time.zone).change(year: d.year, month: d.month, day: d.day, hour: hour, min: 0)
  end

end

app/views/admin/orders/_form.haml
= stylesheet_link_tag 'order_page'
= javascript_include_tag 'order_page'

%input{name: 'objects_serialized', value: @resource_manager.objects, id: 'objects_serialized', type: 'hidden'}
%input{name: 'characters_serialized', value: @resource_manager.characters, id: 'characters_serialized', type: 'hidden'}
%input{name: 'actors_serialized', value: @resource_manager.actors, id: 'actors_serialized', type: 'hidden'}
%input{name: 'stages_serialized', value: @resource_manager.stages, id: 'stages_serialized', type: 'hidden'}
%input{name: 'customer_serialized', value: @resource_manager.customers, id: 'customer_serialized', type: 'hidden'}

= form_for [:admin, @order], html: {id: 'order_form'} do |f|
  %input{name: 'order[is_new_order]', class: 'form-control input-sm',
         value: @order.is_new_order ? 1 : 0, id: 'order_mode', type: 'hidden'}

  %input{name: 'order[is_new_stage]', class: 'form-control input-sm',
         value: @order.is_new_stage ? 1 : 0, id: 'stage_mode', type: 'hidden'}

  .container-fluid

    .row
      .col-md-2.order_row
        .btn-group-sm{role: 'group', aria: {label: '...'}}
          - css_class = @order.is_new_order ? 'default' : 'primary'
          %button{type: 'button', class: "customer_switcher btn btn-#{css_class}", data: {object: 'existing_customer', value: 0}}
            Повторник
          - css_class = @order.is_new_order ? 'primary' : 'default'
          %button{type: 'button', class: "customer_switcher btn btn-#{css_class}", data: {object: 'new_customer', value: 1}}
            Новый заказ
      .col-md-2


        .btn-group-sm{role: 'group', aria: {label: '...'}}
          - css_class = @manager.customer.physical? ? 'primary' : 'default'
          %button{type: 'button', class: "customer_type_switcher btn btn-#{css_class}",
            data: {value: Customer.customer_types[:physical]}}
            Физ. лицо

          - css_class = @manager.customer.partner? ? 'primary' : 'default'
          %button{type: 'button', class: "customer_type_switcher btn btn-#{css_class}",
            data: {value: Customer.customer_types[:partner]}}
            Партнер

    -# ------------------------------------ Customer ----------------------------------
    .row.header_row
      .col-md-2.input_header
        Информация о заказчике

    .row.header_row.customer_block.new_customer{style: @order.is_new_order ? '' : 'display:none'}
      .col-md-2
        Заказчик
      .col-md-2
        Контакт
      .col-md-2
        Примечание к контакту

    -# TODO: remove contact name, contact phone (value) from order
    .row.header_row.customer_block.new_customer{style: @order.is_new_order ? '' : 'display:none'}

      .col-md-2.error_container
        %input{name: 'order[customer][name]', class: 'form-control input-sm'}
        .error_message

        %input{name: 'order[customer][customer_type]', class: 'form-control input-sm',
               value: Customer.customer_types[@manager.customer.customer_type], id: 'customer_type', type: 'hidden'}

      .col-md-2.error_container
        %input{name: 'order[contact][value]', class: 'form-control input-sm', id: 'contact_value'}
        .error_message

      .col-md-2.error_container
        %input{name: 'order[contact][notice]', class: 'form-control input-sm'}
        .error_message

    .row.header_row.customer_block.existing_customer{style: @order.is_new_order ? 'display:none' : ''}
      .col-md-2
        Заказчик
      .col-md-1
        Контакт
      .col-md-1.action_link
        = link_to new_admin_contact_path, target: '_blank', title: 'Добавить контакт' do
          %span.glyphicon.glyphicon-plus
        = link_to '#', target: '_blank', title: 'Обновить список', class: 'updater', data: {name: 'contacts'} do
          %span.glyphicon.glyphicon-refresh

    .row.order_row.customer_block.existing_customer{style: @order.is_new_order ? 'display:none' : ''}

      .col-md-2.error_container
        = f.collection_select :customer_id, Customer.all, :id, :name, {prompt: 'Не выбрано'},
        {class: 'form-control input-sm', id: 'customer_selector'}
        .error_message

      .col-md-2.error_container
        = f.collection_select :contact_id, Contact.where(customer_id: @manager.contact.customer_id), :id, :description,
        {prompt: 'Не выбрано', selected: @manager.contact.id}, {class: 'form-control input-sm'}
        .error_message

    -# ------------------------------------ Stage ----------------------------------
    .row.header_row
      .col-md-2.input_header
        Место проведения

    .row.header_row
      .col-md-4
        .btn-group-xs{role: 'group', aria: {label: '...'}}
          - css_class = @order.is_new_stage ? 'default' : 'primary'
          %button{type: 'button', class: "stage_switcher btn btn-#{css_class}", data: {value: '0'}}
            площадка
          - css_class = @order.is_new_stage ? 'primary' : 'default'
          %button{type: 'button', class: "stage_switcher btn btn-#{css_class}", data: {value: '1'}}
            на дому
          %button{type: 'button', class: 'stage_switcher btn btn-default', data: {value: '2'}}
            у заказчика

    .row.header_row
      .col-md-1
        Площадка
      .col-md-1.action_link
        %div.stage_constructors
          = link_to new_admin_stage_path, target: '_blank', title: 'Добавить площадку' do
            %span.glyphicon.glyphicon-plus
          = link_to '#', target: '_blank', title: 'Обновить список', class: 'stage_updater' do
            %span.glyphicon.glyphicon-refresh

      .col-md-1
        Район
      .col-md-2
        Улица
      .col-md-1
        Дом
      .col-md-1
        Квартира
      .col-md-2
        Примечание
    .row.order_row.stage_inputs

      .col-md-2.error_container
        = f.collection_select :stage_id, Stage.all, :id, :name, {prompt: 'Не выбрано'}, {class: 'form-control input-sm',  id: 'stages_selector'}
        .error_message

      .col-md-1
        %select{class: 'form-control input-sm', id: 'district_selector', name: 'order[stage][district]'}
          - District.all.each do |district|
            %option{value: "#{district.id}"}
              = district.name

      .col-md-2.error_container
        %input{name: 'order[stage][street]', class: 'form-control input-sm'}
        .error_message

      .col-md-1.error_container
        %input{name: 'order[stage][house]', class: 'form-control input-sm'}
        .error_message

      .col-md-1.error_container
        %input{name: 'order[stage][apartment]', class: 'form-control input-sm'}
        .error_message

      .col-md-2
        %input{name: 'order[stage][description]', class: 'form-control input-sm'}

    .row.separator
    -# ------------------------------------ ORDER SOURCE
    .row.header_row.source_template_part
      .col-md-1
        Источник заказа
      .col-md-1.action_link
        = link_to new_admin_order_source_path, target: '_blank', title: 'Добавить источник' do
          %span.glyphicon.glyphicon-plus
        = link_to '#', target: '_blank', title: 'Обновить список', class: 'source_updater', data: {name: 'order_sources'} do
          %span.glyphicon.glyphicon-refresh

    .row.order_row.source_template_part
      .col-md-2
        = f.select :order_source_id, OrderSource.all.map{|r| [r.value, r.id]}, {}, class: 'form-control input-sm',
          value: @order.order_source_id
    .row.separator.source_template_part
    -# ------------------------------------ ORDER STATUS
    .row.header_row.source_template_part
      .col-md-1
        Статус заказа

    .row.order_row
      .col-md-2
        = f.select :status, Order.statuses.map{|k, v| [t("admin.order.statuses.#{k}"), k]}, {}, class: 'form-control input-sm'
    -# ------------------------------------ CHILD
    .row.header_row
      .col-md-2.input_header
        Именинник

    .row.header_row
      .col-md-2
        Имя ребенка
      .col-md-2
        Дата рождения
      -#.col-md-2
        возраст гостей
      .col-md-1
        Примечание

    .row.order_row

      .col-md-2.error_container
        = f.text_field :child_name, class: 'form-control input-sm'
        .error_message

      .col-md-2.error_container
        .input-group.date.date_picker
          = f.text_field :child_birthday, value: @order.child_birthday.strftime('%d.%m.%Y'), class: 'form-control input-sm'
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        .error_message

      .col-md-2.error_container
        = f.text_field :child_notice, class: 'form-control input-sm'
        .error_message

    .row.header_row
      .col-md-2
        Возраст гостей

    .row.order_row
      .col-md-1.error_container
        =f.text_field :guests_age_from, class: 'form-control input-sm'
        .error_message
      .col-md-1.error_container
        =f.text_field :guests_age_to, class: 'form-control input-sm'
        .error_message

    .row.separator

    .row.header_row
      .col-md-2
        дата
      .col-md-2
        время начала
      .col-md-1
        продолжительность
      .col-md-1.action_link
        = link_to '30', '#', class: 'fast_duration', data: {value: 30}
        = '/'
        = link_to '45', '#', class: 'fast_duration', data: {value: 45}
        = '/'
        = link_to '60', '#', class: 'fast_duration', data: {value: 60}
    .row.order_row
      .col-md-2.error_container
        %div.input-group.date.date_picker
          =f.text_field :performance_date, value: @order.performance_date.strftime('%d.%m.%Y'),
            class: 'form-control input-sm'
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        .error_message

      .col-md-2.error_container
        %div.input-group.date.time_picker
          =f.text_field :performance_time, class: 'form-control input-sm'
          %span.input-group-addon
            %span.glyphicon.glyphicon-time
        .error_message

      .col-md-2
        =f.select :performance_duration, Duration::AVAILABLE_DURATIONS.map{|i| ["#{i} минут", i]}, {},
          class: 'form-control input-sm', value: @order.performance_duration || 60

      .col-md-3#available_characters_count
        доступно объектов: Х

    .row.header_row
      .col-md-3.input_header
        Добавить персонаж/программу к заказу
    - if @order.persisted?
      - if @manager.owners.any?
        - @manager.owners.each_with_index do |object, index|
          = render partial: 'object_selector', locals: {id: index, object: object}
      - else
        = render partial: 'object_selector', locals: {id: 1, object: nil}

    - else
      = render partial: 'object_selector', locals: {id: 1, object: nil}


    .row.separator

    .row.header_row
      .col-md-2.input_header
        Финансы заказа

    .row
      .col-md-2
        .row.header_row
          .col-md-5
            Партнерские
          .col-md-5.action_link
            = link_to '  по прайсу', '#'
        .row.order_row
          .col-md-5
            .input-group
              = text_field_tag 'partner_money_percents', 0, class: 'form-control input-sm'
              %span{class: 'input-group-addon partner_percents_radio selected'}
                = '%'
          .col-md-6
            .input-group
              = f.text_field :partner_money, value: @order.partner_money || 0, class: 'form-control input-sm'
              %span{class: 'input-group-addon partner_amount_radio'}
                %span.glyphicon.glyphicon-rub

      .col-md-2
        = f.check_box :exclude_additional_expense, id: 'exclude_additional_expense', value: @order.exclude_additional_expense
        не считать допники на партнерских
        %br
        = f.check_box :exclude_outcome, id: 'exclude_outcome', value: @order.exclude_outcome
        процент от прибыли
        %br
        = f.check_box :partner_payed, value: @order.partner_payed
        партнерские оплачены

      .col-md-3
        .row.header_row
          .col-md-6
            Стоймость допников
          .col-md-6
            Примечание
        .row.order_row
          .col-md-6.error_container
            .input-group
              = f.text_field :additional_expense, value: @order.additional_expense || 0, class: 'form-control input-sm', id: 'additional_expense'
              %span.input-group-addon
                %span.glyphicon.glyphicon-rub
            .error_message

          .col-md-6
            = f.text_field :order_calculations_notice, class: 'form-control input-sm'

    .row.submit_actions
      = f.submit 'Сохранить', class: 'btn-small btn-primary', id: 'submit_order_btn'
      = link_to 'Отмена', '#'

app/views/admin/orders/_object.html.haml
- character = position.character

.div{class: 'order_object', data: {object_id: position.id}}
  .row
    .special_head_row.header
      = Order::Objects::Presenter.character_full_name(character)
    .sub_header.first.costume_occupation
      %span
        костюм
      %span.glyphicon.glyphicon-ok-sign
    .sub_header.actor_occupation
      %span
        аниматор
      %span.glyphicon.glyphicon-ok-sign

  .row.header_row
    .col-md-1
      время начала

    .col-md-1.action_link
      = check_box_tag "order[positions][#{index}][fixed_start]", 1, position.fixed_start, class: 'fixed_position_start'
      %span
        как в заказе

    .col-md-1
      время окончания

    .col-md-1.action_link
      = check_box_tag "order[positions][#{index}][fixed_stop]", 1, position.fixed_stop, class: 'fixed_position_stop'
      %span
        как в заказе

    .col-md-1
      стоймость

    .col-md-1.action_link
      = check_box_tag "order[positions][#{index}][payed]", 1, position.payed
      оплачено

    .col-md-1
      гонорар актера

    .col-md-1.action_link
      = check_box_tag "order[positions][#{index}][animator_payed]", 1, position.animator_payed
      оплачено

    .col-md-2
      накладные

  .row.order_row

    .col-md-2.error_container
      %div.input-group.date.time_picker
        %input{name: "order[positions][#{index}][start]", class: 'form-control input-sm position_start_time',
        value: position.start.strftime('%H:%M')}
        %span.input-group-addon
          %span.glyphicon.glyphicon-time
      .error_message

    .col-md-2.error_container
      %div.input-group.date.time_picker
        %input{name: "order[positions][#{index}][stop]", class: 'form-control input-sm position_stop_time',
        value: position.stop.strftime('%H:%M')}
        %span.input-group-addon
          %span.glyphicon.glyphicon-time
      .error_message

    .col-md-2.error_container
      .input-group.input-group-sm
        %input{name: "order[positions][#{index}][price]", class: 'form-control input-sm position_price',
          value: position.price}
        %span{class: 'input-group-addon', title: 'Вставить из прайса'}
          %span{class: 'glyphicon glyphicon-th-list load_from_price', data: {attribute: 'price'}}
      .error_message

    .col-md-2.error_container
      .input-group.input-group-sm
        %input{name: "order[positions][#{index}][animator_money]", class: 'form-control input-sm position_animator_money',
          value: position.animator_money}
        %span{class: 'input-group-addon', title: 'Вставить из прайса'}
          %span{class: 'glyphicon glyphicon-th-list load_from_price', data: {attribute: 'animator_money'}}
      .error_message

    .col-md-2.error_container
      %input{name: "order[positions][#{index}][overheads]", class: 'form-control input-sm position_overheads',
      value: position.overheads}
      .error_message

    %input{name: "order[positions][#{index}][character_id]", class: 'form-control input-sm character_id_hidden', type: 'hidden',
    value: character.id }
    %input{name: "order[positions][#{index}][owner_class]", class: 'form-control input-sm', type: 'hidden',
    value: owner.class}
    %input{name: "order[positions][#{index}][owner_id]", class: 'form-control input-sm', type: 'hidden',
    value: owner.id}

  .row.header_row
    .col-md-3
      Примечание к заказу
    .col-md-3
      Информация для актера
  .row.order_row
    .col-md-3
      = text_area_tag "order[positions][#{index}][order_notice]", position.order_notice,
      class: 'form-control input-sm', size: 20
    .col-md-3
      = text_area_tag "order[positions][#{index}][actor_notice]", position.actor_notice,
      class: 'form-control input-sm', size: 20

  .row.order_row
    .error_container.col-md-3
      %div{name: "order[positions][#{index}][actors]"}
      %div.error_message.actors_error

  = render partial: 'position_actors', locals: {position: position, index: index}

app/views/admin/orders/_object_selector.haml
%div{id: "order_object_container_#{id}", class: 'container-fluid order_object_container order_row'}
  .row
    .col-md-2.error_container
      = select_tag 'order_object_selector_0',
        options_for_select(Order::Objects::Presenter.all_order_objects, Order::Objects::Presenter.object_value(object)),
        include_blank: 'Не выбрано', class: 'form-control input-sm order_object_selector',
        data: {object_index: id}

      %div{name: 'order[invitations]'}
      %div.error_message

    .col-md-2.action_link
      %a.add_order_object{href: '#', style: 'display: none', title: 'Добавить персонаж/программу'}
        %span.glyphicon.glyphicon-plus
      %a.remove_order_object{href: '#', style: 'display: none', title: 'Исключить персонаж/программу'}
        %span.glyphicon.glyphicon-trash

  - if @order.persisted?
    - positions = @manager.owner_positions(object)
    - if positions.any?
      - positions.each_with_index do |position, index|
        = render partial: 'object', locals: {index: index + id * 100,
        position: position, owner: object}

app/views/admin/orders/_position_actors.haml
- Actor.order(:name).each_slice(3) do |slice|
  .row.order_row.actor_row
    - slice.each do |actor|
      - invitation = @actor_manager.actor_invitation(actor, position)

      - invited = @actor_manager.actor_invited?(actor, position)
      - occupied = @actor_manager.actor_occupied?(actor, position)
      - blocked = @actor_manager.actor_blocked?(actor, position)

      - if occupied
        %div{class: 'col-md-2 actor_name occupied'}
          = check_box_tag "order[positions][#{index}][actors][#{actor.id}][checked]", 1, false, disabled: true
          %span{title: 'Актер занят на другом заказе'}
            = actor.name
        .col-md-1.actor_corrector.occupied
          %input{class: 'form-control input-sm', name: "order[positions][#{index}][actors][#{actor.id}][corrector]",
            value: 0.0, title: 'Актер занят на другом заказе', disabled: true}

      - elsif invited
        %div{class: 'col-md-2 actor_name invited'}
          = check_box_tag "order[positions][#{index}][actors][#{actor.id}][checked]", 1, true
          %span{title: 'Актер уже приглашен'}
            = actor.name
        .col-md-1.actor_corrector
          %input{class: 'form-control input-sm', name: "order[positions][#{index}][actors][#{actor.id}][corrector]",
            value: invitation.corrector, title: 'Корректор'}

      - elsif blocked
        -# do not show actors if they are blocked for this character
        -#%div{class: 'col-md-2 actor_name blocked'}
        -#  = check_box_tag "order[positions][#{index}][actors][#{actor.id}][checked]", 1, false, disabled: true
        -#  %span{title: 'Актер не подходит на эту роль'}
        -#    = actor.name
        -#.col-md-1.actor_corrector.blocked
        -#  %input{ class: 'form-control input-sm', name: "order[positions][#{index}][actors][#{actor.id}][corrector]",
        -#    value: 0.0, title: 'Корректор', disabled: true}

      - else
        %div{class: 'col-md-2 actor_name'}
          = check_box_tag "order[positions][#{index}][actors][#{actor.id}][checked]", 1, false
          %span{title: 'Актер доступен для выбора'}
            = actor.name
        .col-md-1.actor_corrector
          %input{class: 'form-control input-sm', name: "order[positions][#{index}][actors][#{actor.id}][corrector]",
            value: 0.0, title: 'Корректор актера'}

app/views/admin/orders/_positions.haml
= stylesheet_link_tag 'invitations_list'
= javascript_include_tag 'invitation_states_switcher'

%table.positions_list
  %thead
    %th{style: 'width: 10%'}
      Выступление
    %th{style: 'width: 5%'}
      Персонаж
    -#%th{style: 'width: 5%'}
      Статус
    %th{style: 'width: 10%'}
      Время
    %th{style: 'width: 5%'}
      Оплачено
    %th{style: 'width: 5%'}
      Цена
    %th{style: 'width: 7%'}
      ЗП аниматора
    %th{style: 'width: 7%'}
      Оплачено
    %th{style: 'width: 7%'}
      Допники
    %th
      Приглашения

  %tbody
    - positions.each_with_index do |position, index|
      %tr
        %td
          = Order::Objects::Presenter.object_name(position.owner)
        %td
          = link_to position.character.name, admin_character_path(position.character)
        %td{title: "Позиция номер #{position.id}"}
          = l(position.start, format: '%d %b, %H:%M')
          = ' - '
          = position.stop.strftime('%H:%M')
        %td
          = position.price
          руб.
        %td
          - if position.payed
            %span.status_tag.yes
              Да
          - else
            %span.status_tag.no
              Нет

        %td
          = position.animator_money
          руб.
        %td
          - if position.animator_payed
            %span.status_tag.yes
              Да
          - else
            %span.status_tag.no
              Нет

        %td
          = position.overheads
          руб.
        %td
          .invitations_list
            - if index.zero?
              .list_head
                .actor_name
                  Имя актера
                .actor_corrector
                  Корректор
                .actor_status
                  Статус
                .actor_actions
                  Действия

            - invitations = position.invitations
            - invitations.each_with_index do |invitation, i|
              - last_row = i != invitations.count - 1
              %div{class: "invitation_block #{ last_row ? 'not_last' : '' }", data: { id: invitation.id }}
                %div{class: 'actor_name', title: "Приглашение номер #{invitation.id}"}
                  = link_to invitation.actor.name, admin_actor_path(invitation.actor)
                .actor_corrector
                  = invitation.corrector
                  руб.
                .actor_status
                  = t("admin.invitation.statuses.#{invitation.status}")
                .actor_actions
                  - invitation.admin_events.each do |event|
                    = link_to(t("admin.invitation.events.#{event}"),
                        fire_event_admin_invitation_path(id: invitation.id, event_name: event))
                    %br